dist: trusty
sudo: required

language: node_js
node_js:
  - "v12.13.0"

cache:
  directories:
    - node_modules

before_install:
  - ./ci/preinstall.sh
  - sudo apt-get install -y dpkg
  - sudo apt-get install chromium-browser
  - sudo apt-get install -f

install:
  - npm install

script:
  - npm run test:travis
