dist: trusty
sudo: required

language: node_js
node_js:
  - "v12.13.0"

env:
  global:
    CODECOV_TOKEN=$CODECOV_TOKEN

cache:
  directories:
    - node_modules

before_install:
  - ./ci/preinstall.sh
  - sudo apt-get install -y dpkg
  - sudo apt-get install chromium-browser
  - sudo apt-get install -f

install:
  - npm install

script:
  - npm run test:travis
  - codecov -f coverage/*.json

after_script:
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./node_modules/.bin/codecov; fi